<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-B6GUK874" failures="1" tests="1" name="Default test(failed)" time="38.748" errors="0" timestamp="2022-06-16T09:24:59 IST">
  <testcase classname="TestCases.SoftAssertionTest" name="verifyemailtest" time="4.195">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1makarandtemkar1333@gmail.com] but found [makarandtemkar1333@gmail.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1makarandtemkar1333@gmail.com] but found [makarandtemkar1333@gmail.com]
at TestCases.SoftAssertionTest.verifyemailtest(SoftAssertionTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyemailtest -->
  <testcase classname="TestCases.SoftAssertionTest" name="verifyusernametest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyusernametest -->
  <testcase classname="TestCases.SoftAssertionTest" name="gttplaceorderTest" time="0.0">
    <ignored/>
  </testcase> <!-- gttplaceorderTest -->
</testsuite> <!-- Default test(failed) -->
